version: 2
jobs:
  build-and-test:
    docker:
      - image: debian:streach
    steps:
      - checkout
      - run:
          name: Build And Test
          command: echo 'build and test'

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test