version: 2
defaults:
  filters: &default_filters
    branches:
      ignore:
        - release
        - master
        - develop
        - hotfix
jobs:
  build-and-test:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Build And Test
          command: echo 'build and test'

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
          filters: *default_filters