name: Push to develop from release
# GitHub API TOKENとSLACK WEBHOOKはsecretに登録する 
on:
  push:
    branches:
      - master

env:
  GITHUB_API_TOKEN: ${{ secrets.GITHUB_API }}

jobs:
  push-to-develop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: disable branch protection
      env:
        JSON: .github/protect_rules/disable.json
        TARGET_BRANCH: develop
      run: sh .github/scripts/gitProtect.sh
    - name: push to develop branch
      env:
        TARGET_BRANCH: develop
        SOURCE_BRANCH: master
      run: sh .github/scripts/gitPush.sh
    - name: enable branch protection
      env:
        JSON: .github/protect_rules/develop.json
        TARGET_BRANCH: develop
      run: sh .github/scripts/gitProtect.sh
    - name: Slack success notification
      if: success()
      run: echo "success" # slack通知
    - name: Slack failure notification
      if: failure()
      run: echo "failure" # slack通知

  push-to-release:
    needs: push-to-develop
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: disable branch protection
      env:
        JSON: .github/protect_rules/disable.json
        TARGET_BRANCH: release
      run: sh .github/scripts/gitProtect.sh
    - name: push to release branch
      env:
        TARGET_BRANCH: release
        SOURCE_BRANCH: master
      run: sh .github/scripts/gitPush.sh
    - name: enable branch protection
      env:
        JSON: .github/protect_rules/develop.json
        TARGET_BRANCH: release
    - name: Slack success notification
      if: success()
      run: echo "success" # slack通知
    - name: Slack failure notification
      if: failure()
      run: echo "failure" # slack通知